apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vend-build-config
  labels:
    app: vend-app
spec:
  nodeSelector: null
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'GIT_REPO_1'
      ref: vend-internal-vpc-route
    contextDir: /
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: IMAGE_STREAM_1:latest
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: vend-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: vend-github-webhook-secret