apiVersion: v1
kind: Service
metadata:
  name: vend-sec-vpc-nlb-us-south-1
  labels:
    customerLoadbalancer: vend-application
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "private"
    service.kubernetes.io/ibm-load-balancer-cloud-provider-zone: "us-south-1"
spec:
  type: LoadBalancer
  selector:
    privateLoadbalancer: vend-application
  ports:
   - name: http
     protocol: TCP
     port: 8080
  externalTrafficPolicy: Local